### ISSUE TITLE
Dialer app crash

### ISSUE THREAD

**Issue by shalzz** [iptux/XCallRecording-xposed#34]
While having the module enabled, the dialer app starts crashing after a while when manually launching the app.
I have the logcat attached below and it seems like an SQLite constraint error, however I didn't see this error before enabling the module.
I have tried clearing the dialer storage multiple times and the error keeps recurring after a while.

```
03-29 13:26:17.367 20962  9036 E SQLiteDatabase: Error inserting title_key= bucket_display_name=Call Recordings owner_package_name=com.android.dialer parent=172 volume_name=external_primary title_resource_uri=null _display_name=2021-03-20 datetaken=1617004577355 mime_type=audio/* _data=/storage/emulated/0/Music/Call Recordings/2021-03-20 title= artist_id=1 is_pending=1 date_added=1617004577 album_id=8 primary_directory=Music secondary_directory=Call Recordings bucket_id=1242809120 media_type=2 relative_path=Music/Call Recordings/
03-29 13:26:17.367 20962  9036 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2713)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3089)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:2916)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:154)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.os.Binder.execTransactInternal(Binder.java:1021)
03-29 13:26:17.367 20962  9036 E SQLiteDatabase:        at android.os.Binder.execTransact(Binder.java:994)
03-29 13:26:17.368 30489 30489 D AndroidRuntime: Shutting down VM
03-29 13:26:17.368 30489 30489 E AndroidRuntime: FATAL EXCEPTION: main
03-29 13:26:17.368 30489 30489 E AndroidRuntime: Process: com.android.dialer, PID: 30489
03-29 13:26:17.368 30489 30489 E AndroidRuntime: java.lang.NullPointerException: uri
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1477)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1227)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1203)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at com.android.dialer.callrecord.CallRecordingAutoMigrator.autoMigrate(CallRecordingAutoMigrator.java:15)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at com.android.dialer.callrecord.CallRecordingAutoMigrator.lambda$fYMd2hq3Rmwh88rOPL23tA-hETA(Unknown Source:0)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at com.android.dialer.callrecord.-$$Lambda$CallRecordingAutoMigrator$fYMd2hq3Rmwh88rOPL23tA-hETA.onSuccess(Unknown Source:8)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at com.android.dialer.common.concurrent.DefaultDialerExecutorFactory$NonUiDialerExecutor.lambda$run$5$DefaultDialerExecutorFactory$NonUiDialerExecutor(DefaultDialerExecutorFactory.java:1)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at com.android.dialer.common.concurrent.-$$Lambda$DefaultDialerExecutorFactory$NonUiDialerExecutor$4t4zo-dgjmLhH8yi_urZa6URxWg.run(Unknown Source:4)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
03-29 13:26:17.368 30489 30489 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
````

ROM: LineageOS 17.1 (android 10)
Note I do not have any "Recording File" options/settings enabled.

**Comment by iptux** [comment]
`CallRecordingAutoMigrator` did not handle directory in `/sdcard/CallRecording/`. `openOutputStream()` on a directory will throw a NPE.

**Comment by shalzz** [comment]
Oh I see, another app had created the directory at the sdcard root and was the culprit. Thanks for the help!
